---
title: "Final Project"
echo: false
jupyter: python3
---

In the last month of the semester you will pair up with another student to do your **Final Project**.
This project is an opportunity for you to apply all what we learned, to be inovative, and create your own agrotech project.
You will have a few weeks to plan, setup and run your projects. At the end of the semester we will have a festive presentation day in which each pair of students will present their projects.

## Updates

Please consult this [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1CezZGCu0f9x4Lwgyo90v1QF-MEy30XM4f_ydzi3EUMY/edit?usp=sharing) to be up-to-date with what's going on with the various projects.
Every team should update this spreadsheet regularly with the relevant information.

## The platform
This year the final projects will all take place in a greenhouse on campus and will share the theme of data logging and control.
Each team's project will involve irrigation control based on sensor readings (see minimal requirements below), and will include an expansion in whatever way the group finds useful and fun. 

* **Minimal requirements:**
  1. set up environmental sensors, such as temperature, humidity, soil moisture, wind, radiation, etc.
  1. log all the measured data in a dedicated Thingspeak channel.
  1. set up an irrigation control system based on the sensed data.
* **Extra: something cool or creative to add to this basic setup, for example**
  1. extra sensors
  1. graphical user interface such as screen with menus and buttons
  1. calculations based on measurements, such as the Penman equation, using python
  1. optimization of water usage
  1. fertilization through irrigation (fertigation)
  1. alerts in case something malfunctions
  1. consult with the lecturers regarding other ideas
  


## Final Report = GitHub page
Documenting your project well is probably one of the most important lessons you will learn.
Without documentation your projects will not live on and they will end their life right after the semester is over; you will forget what exactly you did and no one will be able to reproduce what you have done.
We don't want that for our projects...  

The goal of the Agrotech-Lab course is to create a repository of all the cool projects made over the years.
That way the projects will live forever and future students and other people around the world can learn from your work.

We require that each team creates a Github page including all the documentation.
It should include:

* **Introduction:** general explanation about the project and its goals
* **Hardware and assembly:** Make the description as detailed as posible. Include many photos, links to order, datasheets etc.
* **Code:** Provide all code used in this project. Code should be organized with comments throughout explaining it.
* **Instructions:** How to make and use the project.
* **Experiment:** Show an example of the project "in action".

Plese note, the github page **is** your "final project paper/report". 

## Presentation

On the last day, when we meet to show our projects, each team will give a short talk of 5 minutes. During this talk you will touch the following points:

* What did you do?
* Why do a project like yours? 
* Are there agricultural or other benefits?
* How did you do it? Hardware and code (no need to go over it, just explain in general).
* What did you learn? Show graphs and data analysis.


> ### Attention!
> Presentation is something you present to others, it does **not** mean a "Powerpoint presentation".
> Your presentation will be solely based on your GitHub repository.