project:
  type: book
  output-dir: docs

book:
  title: "agrotech lab"
  author: "Yair Mau & Erez Feuer"
  favicon: /archive/images/favicon.ico
  # repo-url: https://github.com/yairmau/time-series/
  chapters:
    - index.qmd
    - schedule.qmd
    - part: "**First steps**"
      chapters:
      - arduino-intro-and-links.qmd
      - tutorials/arduino_IDE.qmd
      - tutorials/install_firebeetle.qmd
      - tutorials/firebeetle_documentation.qmd
      - tutorials/breadboard.qmd
    - part: "**Running simple programs**"
      chapters:
      - tutorials/first-programs.qmd
      - tutorials/libraries.qmd
      - tutorials/thingspeak.qmd
      - tutorials/merging.qmd
      - tutorials/SHT31.qmd
      - tutorials/RGB.qmd
    - part: "**Electronics**"
      chapters:
      - tutorials/basic-electronics-concepts.qmd
      - tutorials/electronics-class.qmd
      - tutorials/soldering-and-wires.qmd
      - tutorials/relay.qmd
    - part: "**Sensors and comm**"
      chapters:
      - tutorials/intro-to-sensor-modules-and-thingspeak.qmd
      - tutorials/pulse-sensors.qmd
      - tutorials/digital-read-write.qmd
      - tutorials/MQTT.qmd
      - tutorials/python-matlab-basics.qmd
      - tutorials/API-thingspeak-python.qmd
    - part: "**Agro stuff**"
      chapters:
      - tutorials/water-and-energy-balances.qmd
      - tutorials/psychrometric-chart-and-evaporative-cooling.qmd
    - part: "**Resources**"
      chapters:
      - resources.qmd
    - part: "**Projects**"
      chapters:
      - projects.qmd
      - projects/borrowing-equipment.qmd
      - projects/passover-2023.qmd
      - projects/final-project.qmd

  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
      - icon: bookmark-fill
        href: /sources.html
      - icon: asterisk
        href: /things-to-remember.html
    logo: archive/images/site-logo.png
  search: true

format:
  html:
    include-before-body: _custom_header.html
    theme:
      - flatly
      - custom.scss
    css: custom.scss
    highlight-style: breezedark
    fontsize: 1.2em
    code-line-numbers: true



