project:
  type: website
  output-dir: docs

website:
  title: "agrotech lab"
  favicon: /archive/images/favicon.ico
  navbar:
    logo: /archive/images/site-logo-white.png
    right:
      - about.qmd
      - schedule.qmd
      - tutorials.qmd
      - resources.qmd
      - projects.qmd

format:
  html:
    include-before-body: _custom_header.html
    theme:
      - flatly
      - custom.scss
    css: custom.scss
    highlight-style: breezedark



