---
title: "SHT31 temperature & humidity sensor"
echo: false
jupyter: python3
---

{{< include ../_insert_ino_code.qmd >}}

## Introduction

In this tutorial, we will learn how to use the ESP32 microcontroller with the SHT31 temperature and humidity sensor. We will cover the basics of the sensor, including how it works and how to connect it to an ESP32. We will also learn how to use the Adafruit_SHT31 library to read temperature and humidity values from the sensor. By the end of this tutorial, you will be able to build your own ESP32 and SHT31-based projects.

## SHT31 Sensor

The SHT31 is a high-precision temperature and humidity sensor that can be used in a wide range of applications. It measures temperature and humidity using a capacitive humidity sensor and a band-gap temperature sensor. It has a wide measurement range of -40°C to 125°C for temperature and 0-100% for relative humidity. The SHT31 is a digital sensor, which means it communicates with the microcontroller over a digital interface. See more details on the [Adafruit's github page for the SHT31](https://github.com/adafruit/Adafruit_SHT31
) and full specs on the [SHT31 datasheet](https://www.mouser.com/datasheet/2/682/Sensirion_Humidity_Sensors_SHT3x_Datasheet_digital-971521.pdf).


## Libraries

To use the SHT31 sensor with an ESP32 microcontroller, we will need to use the Adafruit_SHT31 library. This library is specifically designed to work with the SHT31 sensor and makes it easy to read temperature and humidity values from the sensor.

To install the library, follow these steps:

1. Open the Arduino IDE
2. Go to **Sketch > Include Library > Manage Libraries**
3. Search for "Adafruit_SHT31" and click the **Install** button
4. Wait for the library to install

## Wiring

To connect the SHT31 sensor to the ESP32 microcontroller, we will need to use four wires: VCC, GND, SDA, and SCL. Here is a table that shows how to connect the wires:

| SHT31 Pin | ESP32 Pin |
|-----------|-----------|
| VCC       | 3V3       |
| GND       | GND       |
| SDA       | GPIO21    |
| SCL       | GPIO22    |

**Note:** The ESP32's 3V3 pin provides 3.3 volts of power, which is the correct voltage for the SHT31 sensor. Do not use the 5V pin, as it will damage the sensor.

## Code

Here is the code for reading temperature and humidity values from the SHT31 sensor.

```{python}
#| echo: false
#| output: asis
code_source("sht31.ino")
```
